
verison: ' 3.8'


networks: 
  automation_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16


services:

#webser container

web-server:
  image: ngnix:alpine 
  container_name: web-server
  hostname: web-server


  network:
    automation_net:
      ipv4_adrress: 172.20.0.10


port 
